name = "rmt-lms-frontend"
compatibility_date = "2024-01-01"

[env.production]
account_id = ""  # Add your Cloudflare account ID here
zone_id = ""     # Add your zone ID here (optional)

# For Cloudflare Pages
pages_build_output_dir = "out"
